# Generated by Django 5.2.1 on 2025-05-30 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalizacion', '0002_alter_ciudad_options_alter_pais_options_and_more'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='sistema.ciudad'),
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='pais',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
