# Generated by Django 5.2.1 on 2025-05-30 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro_monitoreo', '0001_initial'),
        ('dispositivos', '0001_initial'),
        ('geolocalizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('INCENDIO', 'Incendio'), ('INUNDACION', 'Inundación'), ('SISMO', 'Sismo'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Alerta')),
                ('nivel_urgencia', models.PositiveSmallIntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('generado_por', models.CharField(max_length=30)),
                ('centro_monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro_monitoreo.centromonitoreo')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.dispositivoiot')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.ubicacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
