# Generated by Django 5.2.1 on 2025-05-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centromonitoreo',
            options={'ordering': ['nombre'], 'verbose_name': 'Centro de Monitoreo', 'verbose_name_plural': 'Centros de Monitoreo'},
        ),
        migrations.AddField(
            model_name='centromonitoreo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='centromonitoreo',
            name='creadodate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='centromonitoreo',
            name='creadopor',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centromonitoreo',
            name='editadodate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='centromonitoreo',
            name='editadopor',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centromonitoreo',
            name='eliminadodate',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='centromonitoreo',
            name='eliminadopor',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
