# Generated by Django 5.2.1 on 2025-05-30 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='País')),
                ('creadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('creadodate', models.DateTimeField(auto_now_add=True, null=True)),
                ('editadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('editadodate', models.DateTimeField(auto_now=True, null=True)),
                ('eliminadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('eliminadodate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Provincia')),
                ('creadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('creadodate', models.DateTimeField(auto_now_add=True, null=True)),
                ('editadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('editadodate', models.DateTimeField(auto_now=True, null=True)),
                ('eliminadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('eliminadodate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Estado')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provincias', to='sistema.pais')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('creadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('creadodate', models.DateTimeField(auto_now_add=True, null=True)),
                ('editadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('editadodate', models.DateTimeField(auto_now=True, null=True)),
                ('eliminadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('eliminadodate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Estado')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='sistema.provincia')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
    ]
