# Generated by Django 5.2.1 on 2025-06-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.CharField(blank=True, editable=False, max_length=1024, null=True)),
                ('ruta', models.CharField(blank=True, editable=False, max_length=1024, null=True)),
                ('clase', models.CharField(blank=True, choices=[('LISTA', 'LISTA'), ('ITEM', 'ITEM')], max_length=10, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Mantenimientos', 'MANTENIMIENTOS'), ('Documentos', 'DOCUMENTOS'), ('Procesos', 'PROCESOS'), ('Informes', 'INFORMES'), ('Seguridad', 'SEGURIDAD')], max_length=15, null=True)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('item_orden', models.IntegerField(blank=True, default=0, null=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('creadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('editadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('creadodate', models.DateTimeField(auto_now_add=True)),
                ('editadodate', models.DateTimeField(auto_now=True)),
                ('pcid', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.modulo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['item_orden'],
            },
        ),
        migrations.CreateModel(
            name='ModuloGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('prioridad', models.IntegerField(blank=True, null=True)),
                ('creadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('editadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('creadodate', models.DateTimeField(auto_now_add=True)),
                ('editadodate', models.DateTimeField(auto_now=True)),
                ('pcid', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('grupos', models.ManyToManyField(to='auth.group')),
                ('modulos', models.ManyToManyField(to='seguridad.modulo')),
            ],
            options={
                'verbose_name': 'Grupo de Módulos',
                'verbose_name_plural': 'Grupos de Módulos',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
    ]
