# Generated by Django 5.2.1 on 2025-05-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivoiot',
            options={'ordering': ['-fecha_instalacion'], 'verbose_name': 'Dispositivo IoT', 'verbose_name_plural': 'Dispositivos IoT'},
        ),
        migrations.RemoveField(
            model_name='dispositivoiot',
            name='usuario',
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='creadodate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='creadopor',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='editadodate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='editadopor',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='eliminadodate',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='eliminadopor',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logdispositivo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='logdispositivo',
            name='creadodate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='logdispositivo',
            name='creadopor',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logdispositivo',
            name='editadodate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='logdispositivo',
            name='editadopor',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logdispositivo',
            name='eliminadodate',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='logdispositivo',
            name='eliminadopor',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivoiot',
            name='fecha_instalacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
