# Generated by Django 5.2.1 on 2025-05-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_alter_dispositivoiot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logdispositivo',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'LogDispositivo IoT', 'verbose_name_plural': 'LogDispositivos IoT'},
        ),
    ]
