# Generated by Django 5.2.1 on 2025-05-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventosistema',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Evento de Sistema', 'verbose_name_plural': 'Eventos de Sistema'},
        ),
    ]
